baseURL = "https://hr24.cz"
languageCode = "cs-CS"
title = "HR24"
theme = "hrm-theme"
description = "HRM Handbook is a complete guide to Human Resources Management, covering wide range of topics like recruitment, compensation, development and leadership."
tags = ["tags"]

  [[menu.main]]
    identifier = "about"
    name = "O mně"
    url = "/about/"
    weight = 1

    [[menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags/"
      weight = 2
